export const CartActionType = {
  TOGGLE_CART_VISIBILITY: "TOGGLE_CART_VISIBILITY",
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  INC_ITEM_QUANTITY: "INC_ITEM_QUANTITY",
  DEC_ITEM_QUANTITY: "DEC_ITEM_QUANTITY",
};
